### ISSUE TITLE
injection error on "DarunGrim3Server.exe"

### ISSUE THREAD

**Issue by codeengn** [ohjeongwook/DarunGrim#10] opened 2010-08-24 03:47 UTC
Pressing Start Diffing while IDA is running generates an injection error on "DarunGrim3Server.exe"

**Comment by ohjeongwook** [comment] 2015-02-27 05:14
Can't reproduce this and didn't get any similar issue, closing for now until further complaints coming from anyone else.

**Closed by ohjeongwook** 2015-02-27 05:14 UTC
Labels: IDA 5.7
